//const NEW_VERSION = "new-version";
export const ENDPOINT = {
  LIBRARY: `/library/get-library`,
  FILTERS: `/library/library-filter`,
  DELETE: `library/delete-library`,
  LIBRARYSTATS: `/library/library-stats`,
  LIBRARYCHANGECONSENT: `/library/change-consent`,
  LIBRARYCREATE: `/library/create-library`,
  SPCCREATE: `/library/create-spc`,
  LIBRARYRESETSTATS: `/library/reset-stats`,
  LIBRARYREUPDATETAGS: `/library/update-tags`,
  LIBRARYREADDSUBLINK: `/library/add-subLink`,
  LIBRARYRESUBLINKLISTING: `/library/sublink`,
  LIBRARYGETPOPUP: `/library/get-popup`,
  LIBRARYDETAIL: `/library/user-detail`,
  LIBRARYSAVEPOPUP: `/library/save-pdf-popup`,
  LIBRARYGETARTICLE: `/library/get-pdffile`,
  SPC_PRO_LISTING: `/library/spc-productListing`,
  ADD_SPC_PRODUCT: "/library/add-product",
  LIBRARYGETSPC: `/library/get-spcListing`,
  LIBRARYGETSINGLESPC: `/library/getSpcById`,
  LIBRARYSPCDELETE: `/library/deletespc`,
  READER_LIST_DATA: `/reader/reader`,
  SPC_PRO_DELETE: `/library/spcProductDelete/`,
  SPC_HELPER_LISTING: `/library/spc-helper-listing`,
  SPC_UPDATE: `/library/spc-edit`,
  LIBRARY_DETAIL_BY_ID: `/library/getLibraryDetail`,
  UPDATE_ARTICLE: `/library/update-article`,
  DELETE_PDF_FILE: `/library//delete-pdf-file`,
  UPDATE_PDF_FILE: `/library/update-pdf`,
  READER_CREATE: `/reader/create-reader`,
  ADD_PDF_WORD: `/library/add-pdf-word`,
  READER_USER_DROP: `/reader/user-detail`,
  READER_GET_READER_USER: `/reader/get-reader`,
  UPLOAD_READER_FILE: `/reader/upload-readers`,
  USERTIMELINE: `/reader/get-timetracking`,
  READERSTATUSUPDATE: `/reader/update-status`,
  READERSFILTER: `/reader/get-reader-filter`,
  READERACTIVITY: `/reader/reader-activity`,
  TOPCLIENTS: `/analytics/reader-country`,
  TOPRESELLER: `/analytics/reader-country`,
  TOPSALES: `/analytics/reader-country`,
  ANALYTICS: "/analytics/graph",
  OPENING_BY_COUNTRY: "/analytics/reader-country",
  CONTENTANALYTICS: "/analytics/content-analytics",

  DELIVERYTRENDS: "analytics/trend",
  REPORTS: "analytics/reports",

  CONTENTTYPE:"analytics/content-type",
  CONTENT:"analytics/content",
  TRENDING_TOPIC:"analytics/topic",
  READER_DOWNLOAD: `/reader/reader-file`,
  GETREADERTIMELINEDETAIL: `/reader/get-reader-detail`,
  COUNTRY_REGISTRATION: `analytics/country`,
  ADD_TAGS: `/library/add-tags`,
};
