//const NEW_VERSION = "new-version";
export const ENDPOINT = {
  LIBRARY: `/library/get-library`,
  FILTERS: `/library/library-filter`,
  DELETE: `library/delete-library`,
  LIBRARYSTATS: `/library/library-stats`,
  LIBRARYCHANGECONSENT: `/library/change-consent`,
  LIBRARYCREATE: `/library/create-library`,
  SPCCREATE: `/library/create-spc`,
  LIBRARYRESETSTATS: `/library/reset-stats`,
  LIBRARYREUPDATETAGS: `/library/update-tags`,
  LIBRARYREADDSUBLINK: `/library/add-subLink`,
  LIBRARYRESUBLINKLISTING: `/library/sublink`,
  LIBRARYGETPOPUP: `/library/get-popup`,
  LIBRARYDETAIL: `/library/user-detail`,
  LIBRARYSAVEPOPUP: `/library/save-pdf-popup`,
  LIBRARYGETARTICLE: `/library/get-pdffile`,
  LIBRARY_VIDEO_LISTING: `/library/video-listing`,
  LIBRARY_UPLOAD_VIDEO: `/library/upload-video`,
  SPC_PRO_LISTING: `/library/spc-productListing`,
  ADD_SPC_PRODUCT: "/library/add-product",
  LIBRARYGETSPC: `/library/get-spcListing`,
  LIBRARYGETSINGLESPC: `/library/getSpcById`,
  LIBRARYSPCDELETE: `/library/deletespc`,
  READER_LIST_DATA: `/reader/reader`,
  MARKETING_READER_LIST_DATA: `/reader/marketing_reader`,
  SPC_PRO_DELETE: `/library/spcProductDelete/`,
  SPC_HELPER_LISTING: `/library/spc-helper-listing`,
  SPC_UPDATE: `/library/spc-edit`,
  LIBRARY_DETAIL_BY_ID: `/library/getLibraryDetail`,
  UPDATE_ARTICLE: `/library/update-article`,
  DELETE_PDF_FILE: `/library/delete-pdf-file`,
  UPDATE_PDF_FILE: `/library/update-pdf`,
  READER_CREATE: `/reader/create-reader`,
  ADD_PDF_WORD: `/library/add-pdf-word`,
  READER_USER_DROP: `/reader/user-detail`,
  MARKETING_READER_USER_DROP: `/reader/user-marketing-detail`,
  READER_GET_READER_USER: `/reader/get-reader`,
  UPLOAD_READER_FILE: `/reader/upload-readers`,
  USERTIMELINE: `/reader/get-timetracking`,
  MARKETINGUSERTIMELINE: `/reader/marketing-timetracking`,
  READERSTATUSUPDATE: `/reader/update-status`,
  MARKETINGREADERSTATUSUPDATE: `/reader/update-marketing-status`,
  READERSFILTER: `/reader/get-reader-filter`,
  MARKETINGREADERSFILTER: `/reader/get-marketing-reader-filter`,
  READERACTIVITY: `/reader/reader-activity`,
  MARKETINGREADERACTIVITY: `/reader/marketing-reader-activity`,
  TOPCLIENTS: `/analytics/reader-country`,
  TOPRESELLER: `/analytics/reader-country`,
  TOPSALES: `/analytics/reader-country`,
  ANALYTICS: "/analytics/graph",
  OPENING_BY_COUNTRY: "/analytics/reader-country",
  CONTENTANALYTICS: "/analytics/content-analytics",
  LIBRARY_SUBLINK_ANALYTICS: "/library/sublink-analtyics",
  READERANALYTICS: "/analytics/reader-analytics",
  SUBLINK_READER_ANALYTICS: "library/sublink-reader",
  OCTALATCH_TOTAL_HCP:
    "https://webinar.docintel.app/lmn/api/analytics/octo_lach_stats_sample",
  OCTALATCH_DELIVERY_REGISTRATION:
    "https://webinar.docintel.app/lmn/api/analytics/octa_delivery_registration",

  DELIVERYTRENDS: "analytics/trend",
  //CAMPAINGSTAT: "analytics/campaign-stats",
  CAMPAINGSTAT: "analytics/delivery-campaign-stats",

  MAPLOCATION: `analytics/map-location`,
  SUBLINK_MAPLOCATION: `library/Sublink-country`,
  REPORTS: "analytics/reports",
  CONTENTTYPE: "analytics/content-type",
  CIS_CONTENT_TYPE: "analytics/contentTypeData",
  CONTENT_TYPE_GRAPH: "/analytics/content-type-graph",
  CONTENT: "analytics/content",
  TRENDING_TOPIC: "analytics/topic",
  READER_DOWNLOAD: `/reader/reader-file`,
  MARKETING_READER_DOWNLOAD: `/reader/marketing_reader_file`,
  GETREADERTIMELINEDETAIL: `/reader/get-reader-detail`,
  COUNTRY_REGISTRATION: `analytics/country`,
  ADD_TAGS: `/library/add-tags`,
  INSERTBULKREADERS: `/reader/add-bulk-reader`,
  STATEBYREGION: `/analytics/octa-country`,
  DOWNLOADARTICLEREADERS: `/analytics/download-analytics`,
  DELETEREADER: `/reader/delete-reader`,
  LOGIN: `auth/login`,
  FILTERLIST: `https://webinar.docintel.app/lmn/api/distributes/filters_list`,
  READERLISTING: "reader/get-trail",
  REGISTERRD: `https://medarkive.com/Pages/RegisterRd`,
  EDITSITE: "reader/trailId",
  ADDSITE: "reader/add-trail",
  UPDATESITE: "reader/edit-trail",
  DELETESITE: "reader/delete-trail",
  UPDATE_TOPIC: "library/edit-product/",
  READER_ADD_FEATURES: "/reader/add-features",
  SPCFILTERS: "library/spc-filter",
  CHANGE_PASSWORD: "auth/change-password",
  INFORMED_USER_FORM: "https://webinar.docintel.app/lmn/contact_email",
  READER_REFRESH: "/reader/sync-reader",
  MARKETING_READER_REFRESH: "/reader/sync-marketing-reader",
  LIBRARY_CLONE_ARTICLE: "/library/clone-article",
  WEBINAR_QUESTION: `/auth/questions`,
  POLL_ANSWER: `/auth/poll-answer`,
  EVENT_ID: `/auth/event-data`,

  SITEREGISTER: "/site-registration",
  SITEREGISTERSORT: "/site-registration-sort",

  IRT_COUNT_GRAPH: "/find-irt-count",
  WEBINAR_QUESTION_LISTING: "/auth/webinar-question",
  // RD_SITE_ENGAGEMENT: "/rd_site_engagement",
  RD_SITE_ENGAGEMENT:
    "https://webinar.docintel.app/lmn/api/analytics/rd_site_engagement",
  SITE_REGISTRATION_LIST: "/site-registration-list",
  INDIVIDUAL_TRAINING_COMPLETION: "/training-completion",
  TRAINING_COMPLETION_DROPDOWN: "/training-completion-dropdown",
  TRAINING_COMPLETION_PAGE_CLICK: "/training-completion-page-click",
  MOST_POPULAR_CONTENT: "/most-popular-content",
  MOST_POPULAR_CONTENT_DROPDOWN: "/most-popular-content-dropdown",
  MOST_POPULAR_PAGE_CONTENT: "/most-popular-content_page_wise",
  MOST_POPULAR_SITE_CONTENT: "/most-popular-content_site_wise",
  QUESTION_ANSWER: "/auth/question-answer",
  QUESTION_UPDATE: "/auth/question-update",
  ADD_EVENT_DATA: "/auth/add-event-data",
  EVENT_SUBMIT: "/auth/event-submit",
  EVENT_CLOSE: "/auth/close-submit",
  ADD_WEBINAR_QUESTION: "/auth/add-webinar-question",
  ADD_MARKETING_FEATURES: "/reader/add-marketing-features",
  READER_MARKETING_USER_DROP: `/reader/user-marketing-detail`,
  GET_MARKETING_USER_DROP: `/reader/get-marketing-reader`,
  CREATE_MARKETING_READER: `/reader/create-marketing-reader`,
};
