// //  export const timeline=[
// //     {	



// // 		"date":"2024-08-22 ",
// //             // "IrtInviteTraining": [],
// //             "IrtInviteTraining": [
// //                 {
// //                     "user_id": 2147537073,
// //                     "pdf_id": 4521,
// //                     "action": "New mail received",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-09 ",
// //                     "time": "13:43:37",
// //                     "first_name": "Michael",
// //                     "last_name": "Nordine",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-101",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147534266,
// //                     "pdf_id": 3970,
// //                     "action": "New mail received",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-09 ",
// //                     "time": "12:30:51",
// //                     "first_name": "Johannes",
// //                     "last_name": "Tünnerhoff",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-102",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "IrtCompleteTraining": [],
// //             "AutoMailSent": [],
// //             "BlockedUsers": [],
// //             "NewHCPRegistered": [],
// //             "ContentOpened": [
// //                 {
// //                     "user_id": 2147537027,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380600,
// //                     "date": "2024-08-22 ",
// //                     "time": "12:54:28",
// //                     "first_name": "Anastasiia",
// //                     "last_name": "Nekhaienko",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-246",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380565,
// //                     "date": "2024-08-22 ",
// //                     "time": "11:22:22",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537027,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380327,
// //                     "date": "2024-08-22 ",
// //                     "time": "06:39:23",
// //                     "first_name": "Anastasiia",
// //                     "last_name": "Nekhaienko",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-246",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537027,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380326,
// //                     "date": "2024-08-22 ",
// //                     "time": "06:38:21",
// //                     "first_name": "Anastasiia",
// //                     "last_name": "Nekhaienko",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-246",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537027,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380325,
// //                     "date": "2024-08-22 ",
// //                     "time": "06:35:05",
// //                     "first_name": "Anastasiia",
// //                     "last_name": "Nekhaienko",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-246",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "ContentShared": [],
// //             "IRTIgnoredTraining": [],
// //             "IRTNotCompletedTraining": [],
// //             "IRTStartedTraining": []


// // },

// // {        
// // 		"date": "2024-08-21 ",
// //             "IrtInviteTraining": [],
// //             // "IrtCompleteTraining": [],
// //             "IrtCompleteTraining": [
// //                 {
// //                     "user_id": 2147537073,
// //                     "pdf_id": 4521,
// //                     "action": "Certificate of training issued for IRT Role: Site unblinded pharmacist",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-14 ",
// //                     "time": "11:00:03",
// //                     "first_name": "Michael",
// //                     "last_name": "Nordine",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-101",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "AutoMailSent": [],
// //             "BlockedUsers": [],
// //             "NewHCPRegistered": [],
// //             "ContentOpened": [
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380215,
// //                     "date": "2024-08-21 ",
// //                     "time": "06:31:34",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380210,
// //                     "date": "2024-08-21 ",
// //                     "time": "05:52:48",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380205,
// //                     "date": "2024-08-21 ",
// //                     "time": "03:23:45",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "ContentShared": [],
// //             "IRTIgnoredTraining": [],
// //             "IRTNotCompletedTraining": [],
// //             "IRTStartedTraining": []


// // },

// // {



// // 		 "date": "2024-08-20 ",
// //             "IrtInviteTraining": [],
// //             "IrtCompleteTraining": [],
// //             "AutoMailSent": [],
// //             "BlockedUsers": [],
// //             "NewHCPRegistered": [],
// //             "ContentOpened": [
// //                 {
// //                     "user_id": 2147537073,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380092,
// //                     "date": "2024-08-20 ",
// //                     "time": "07:58:22",
// //                     "first_name": "Michael",
// //                     "last_name": "Nordine",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-101",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537073,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380091,
// //                     "date": "2024-08-20 ",
// //                     "time": "07:58:07",
// //                     "first_name": "Michael",
// //                     "last_name": "Nordine",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-101",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "ContentShared": [],
// //             "IRTIgnoredTraining": [],
// //             "IRTNotCompletedTraining": [],
// //             "IRTStartedTraining": []


// // },

// // {



// // 		"date": "2024-08-19 ",
// //             "IrtInviteTraining": [],
// //             "IrtCompleteTraining": [],
// //             "AutoMailSent": [],
// //             "BlockedUsers": [],
// //             "NewHCPRegistered": [],
// //             "ContentOpened": [
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380071,
// //                     "date": "2024-08-19 ",
// //                     "time": "23:37:19",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380068,
// //                     "date": "2024-08-19 ",
// //                     "time": "20:37:03",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380065,
// //                     "date": "2024-08-19 ",
// //                     "time": "18:32:39",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537024,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380025,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:56:47",
// //                     "first_name": "Stepan",
// //                     "last_name": "Cherniaiev",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380026,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:56:47",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380027,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:56:47",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380028,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:56:47",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380023,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:53:56",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380024,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:53:56",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537024,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380021,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:53:55",
// //                     "first_name": "Stepan",
// //                     "last_name": "Cherniaiev",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380022,
// //                     "date": "2024-08-19 ",
// //                     "time": "10:53:55",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380006,
// //                     "date": "2024-08-19 ",
// //                     "time": "05:17:06",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380004,
// //                     "date": "2024-08-19 ",
// //                     "time": "05:17:05",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380005,
// //                     "date": "2024-08-19 ",
// //                     "time": "05:17:05",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537024,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 380003,
// //                     "date": "2024-08-19 ",
// //                     "time": "05:17:04",
// //                     "first_name": "Stepan",
// //                     "last_name": "Cherniaiev",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "ContentShared": [],
// //             "IRTIgnoredTraining": [],
// //             "IRTNotCompletedTraining": [
// //                 {
// //                     "user_id": 2147533855,
// //                     "pdf_id": 3970,
// //                     "date": "2024-08-19",
// //                     "time": "14:00:03",
// //                     "first_name": "Aysegul ",
// //                     "last_name": "Bilici Secmeler",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-326",
// //                     "action": "IRT Not Completed Training"
// //                 },
// //                 {
// //                     "user_id": 2147534558,
// //                     "pdf_id": 3968,
// //                     "date": "2024-08-19",
// //                     "time": "14:00:03",
// //                     "first_name": "Renata",
// //                     "last_name": "Smajdova",
// //                     "user_type": "Site User-Blinded",
// //                     "site_number": "210-220",
// //                     "action": "IRT Not Completed Training"
// //                 },
// //                 {
// //                     "user_id": 2147533018,
// //                     "pdf_id": 4521,
// //                     "date": "2024-08-19",
// //                     "time": "13:30:03",
// //                     "first_name": "Maria Angelica",
// //                     "last_name": "Rivera Núñez",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-202",
// //                     "action": "IRT Not Completed Training"
// //                 }
// //             ],
// //             "IRTStartedTraining": []


// // },

// // {



// // 		"date": "2024-08-18",
// //             "IrtInviteTraining": [],
// //             "IrtCompleteTraining": [],
// //             "AutoMailSent": [
// //                 {
// //                     "user_id": 2147537037,
// //                     "pdf_id": 4521,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "02:30:02",
// //                     "first_name": "Maxym  ",
// //                     "last_name": "Denysiuk",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537032,
// //                     "pdf_id": 3968,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "02:00:01",
// //                     "first_name": "Anna ",
// //                     "last_name": "Teroshyna",
// //                     "user_type": "Site User-Blinded",
// //                     "site_number": "210-243",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Site User Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537030,
// //                     "pdf_id": 4521,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "01:30:02",
// //                     "first_name": "Tetiana ",
// //                     "last_name": "Yurkiv",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-243",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147536962,
// //                     "pdf_id": 3970,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "01:00:01",
// //                     "first_name": "Canan",
// //                     "last_name": "Gulboy",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-324",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147536958,
// //                     "pdf_id": 4521,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:30:02",
// //                     "first_name": "Omer",
// //                     "last_name": "Gedikli",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-324",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147536960,
// //                     "pdf_id": 4521,
// //                     "action": "New mail received",
// //                     "auto_mail": 1,
// //                     "staticpdf_id": 0,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:30:02",
// //                     "first_name": "Ali Can",
// //                     "last_name": "Ozdemir",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-324",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "BlockedUsers": [],
// //             "NewHCPRegistered": [],
// //             "ContentOpened": [
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379979,
// //                     "date": "2024-08-18 ",
// //                     "time": "12:17:35",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379980,
// //                     "date": "2024-08-18 ",
// //                     "time": "12:17:35",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537024,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379977,
// //                     "date": "2024-08-18 ",
// //                     "time": "12:17:34",
// //                     "first_name": "Stepan",
// //                     "last_name": "Cherniaiev",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379978,
// //                     "date": "2024-08-18 ",
// //                     "time": "12:17:34",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379962,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:59:10",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537023,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379960,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:59:09",
// //                     "first_name": "Olesya ",
// //                     "last_name": "Havrylenko",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537036,
// //                     "pdf_id": 4521,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379961,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:59:09",
// //                     "first_name": "Halyna",
// //                     "last_name": "Poniatovska",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Investigator Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 },
// //                 {
// //                     "user_id": 2147537024,
// //                     "pdf_id": 3970,
// //                     "action": "Article opened",
// //                     "auto_mail": 0,
// //                     "staticpdf_id": 379959,
// //                     "date": "2024-08-18 ",
// //                     "time": "00:59:08",
// //                     "first_name": "Stepan",
// //                     "last_name": "Cherniaiev",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-245",
// //                     "file_type": "video",
// //                     "pdfTitle": "IRT video training - Pharmacist Role",
// //                     "subTitle": "MANDATORY Video for the indicated role to achieve certification"
// //                 }
// //             ],
// //             "ContentShared": [],
// //             "IRTIgnoredTraining": [
// //                 {
// //                     "user_id": 2147536958,
// //                     "pdf_id": 4521,
// //                     "date": "2024-08-18",
// //                     "time": "00:00:07",
// //                     "first_name": "Omer",
// //                     "last_name": "Gedikli",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-324",
// //                     "action": "IRT Ignored Training"
// //                 },
// //                 {
// //                     "user_id": 2147536960,
// //                     "pdf_id": 4521,
// //                     "date": "2024-08-18",
// //                     "time": "00:00:07",
// //                     "first_name": "Ali Can",
// //                     "last_name": "Ozdemir",
// //                     "user_type": "Investigator-Blinded",
// //                     "site_number": "210-324",
// //                     "action": "IRT Ignored Training"
// //                 },
// //                 {
// //                     "user_id": 2147536962,
// //                     "pdf_id": 3970,
// //                     "date": "2024-08-18",
// //                     "time": "00:00:07",
// //                     "first_name": "Canan",
// //                     "last_name": "Gulboy",
// //                     "user_type": "Site unblinded pharmacist",
// //                     "site_number": "210-324",
// //                     "action": "IRT Ignored Training"
// //                 }
// //             ],
// //             "IRTNotCompletedTraining": [],
// //             "IRTStartedTraining": []
// //         }


// // ]

// export const timeline = [


//     {
//         "date": "Aug 25. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380849,
//                 "date": "2024-08-25 ",
//                 "time": "23:43:31",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380844,
//                 "date": "2024-08-25 ",
//                 "time": "17:20:31",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380829,
//                 "date": "2024-08-25 ",
//                 "time": "09:10:42",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537025,
//                 "pdf_id": 3970,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-25 ",
//                 "time": "01:00:01",
//                 "first_name": "Serhii",
//                 "last_name": "Sereda",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380825,
//                 "date": "2024-08-25 ",
//                 "time": "00:54:37",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537019,
//                 "pdf_id": 4521,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-25 ",
//                 "time": "00:30:01",
//                 "first_name": "Olesia",
//                 "last_name": "Kuchma",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-243",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147537019,
//                 "pdf_id": 4521,
//                 "date": "2024-08-25",
//                 "time": "00:00:08",
//                 "first_name": "Olesia",
//                 "last_name": "Kuchma",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-243",
//                 "action": "IRT Ignored Training",
//                 "heading": "IRT Ignored Training"
//             },
//             {
//                 "user_id": 2147537025,
//                 "pdf_id": 3970,
//                 "date": "2024-08-25",
//                 "time": "00:00:08",
//                 "first_name": "Serhii",
//                 "last_name": "Sereda",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-245",
//                 "action": "IRT Ignored Training",
//                 "heading": "IRT Ignored Training"
//             }
//         ]
//     },
//     {
//         "date": "Aug 24. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380820,
//                 "date": "2024-08-24 ",
//                 "time": "16:41:34",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380808,
//                 "date": "2024-08-24 ",
//                 "time": "05:39:04",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 29510,
//                 "pdf_id": 3968,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-24 ",
//                 "time": "00:30:02",
//                 "first_name": "Jacob",
//                 "last_name": "Flindt",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-220",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 29510,
//                 "pdf_id": 3968,
//                 "date": "2024-08-24",
//                 "time": "00:00:08",
//                 "first_name": "Jacob",
//                 "last_name": "Flindt",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-220",
//                 "action": "IRT Ignored Training",
//                 "heading": "IRT Ignored Training"
//             }
//         ]
//     },
//     {
//         "date": "Aug 23. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Reminder To Complete The Assigned IRT Training for IRT Role: Site User-Blinded",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "12:44:42",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380754,
//                 "date": "2024-08-23 ",
//                 "time": "11:41:21",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380753,
//                 "date": "2024-08-23 ",
//                 "time": "11:41:01",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380752,
//                 "date": "2024-08-23 ",
//                 "time": "11:30:44",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537032,
//                 "action": "Registered for Non Mandatory content package",
//                 "send_by": 2147501188,
//                 "app_used": "LEX-Registration-Page",
//                 "first_name": "Anna ",
//                 "last_name": "Teroshyna",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-243",
//                 "date": "2024-08-23 ",
//                 "time": "10:29:35",
//                 "heading": "New HCP Registered"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380735,
//                 "date": "2024-08-23 ",
//                 "time": "10:12:51",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380734,
//                 "date": "2024-08-23 ",
//                 "time": "10:09:20",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3970,
//                 "date": "2024-08-23",
//                 "time": "10:09:20",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "action": "IRT Started Training",
//                 "heading": "IRT Started Training"
//             },
//             {
//                 "user_id": 2147537032,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380733,
//                 "date": "2024-08-23 ",
//                 "time": "10:07:55",
//                 "first_name": "Anna ",
//                 "last_name": "Teroshyna",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-243",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537032,
//                 "pdf_id": 3968,
//                 "date": "2024-08-23",
//                 "time": "10:07:54",
//                 "first_name": "Anna ",
//                 "last_name": "Teroshyna",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-243",
//                 "action": "IRT Started Training",
//                 "heading": "IRT Started Training"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3970,
//                 "action": "New mail received",
//                 "auto_mail": 0,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "10:01:04",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "IRT Invited to the Training"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "New mail received",
//                 "auto_mail": 0,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "09:53:20",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "IRT Invited to the Training"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380726,
//                 "date": "2024-08-23 ",
//                 "time": "09:11:01",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 4521,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "06:44:32",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 4521,
//                 "action": "New mail received",
//                 "auto_mail": 0,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "06:36:57",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "IRT Invited to the Training"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380703,
//                 "date": "2024-08-23 ",
//                 "time": "06:31:58",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "06:30:01",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "06:25:55",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "Auto New mail received",
//                 "auto_mail": 1,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "06:00:02",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Auto Email sent"
//             },
//             {
//                 "user_id": 2147501106,
//                 "pdf_id": 3968,
//                 "action": "New mail received",
//                 "auto_mail": 0,
//                 "staticpdf_id": 0,
//                 "date": "2024-08-23 ",
//                 "time": "05:51:42",
//                 "first_name": "aamir",
//                 "last_name": "saleem",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-261",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Site User Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "IRT Invited to the Training"
//             }
//         ]
//     },
//     {
//         "date": "Aug 22. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537027,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380600,
//                 "date": "2024-08-22 ",
//                 "time": "12:54:28",
//                 "first_name": "Anastasiia",
//                 "last_name": "Nekhaienko",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-246",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380565,
//                 "date": "2024-08-22 ",
//                 "time": "11:22:22",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537027,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380327,
//                 "date": "2024-08-22 ",
//                 "time": "06:39:23",
//                 "first_name": "Anastasiia",
//                 "last_name": "Nekhaienko",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-246",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537027,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380326,
//                 "date": "2024-08-22 ",
//                 "time": "06:38:21",
//                 "first_name": "Anastasiia",
//                 "last_name": "Nekhaienko",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-246",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537027,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380325,
//                 "date": "2024-08-22 ",
//                 "time": "06:35:05",
//                 "first_name": "Anastasiia",
//                 "last_name": "Nekhaienko",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-246",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             }
//         ]
//     },

//     {
//         "date": "Aug 21.2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380215,
//                 "date": "2024-08-21 ",
//                 "time": "06:31:34",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380210,
//                 "date": "2024-08-21 ",
//                 "time": "05:52:48",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380205,
//                 "date": "2024-08-21 ",
//                 "time": "03:23:45",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             }
//         ]
//     },

//     {
//         "date":"Aug 20. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537073,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380092,
//                 "date": "2024-08-20 ",
//                 "time": "07:58:22",
//                 "first_name": "Michael",
//                 "last_name": "Nordine",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-101",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537073,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380091,
//                 "date": "2024-08-20 ",
//                 "time": "07:58:07",
//                 "first_name": "Michael",
//                 "last_name": "Nordine",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-101",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "heading": "Content Opened"
//             }
//         ]
//     },
//     {
//         "date":"Aug 19. 2024",
//         "IrtData": [
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380071,
//                 "date": "2024-08-19 ",
//                 "time": "23:37",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380068,
//                 "date": "2024-08-19 ",
//                 "time": "20:37",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537036,
//                 "pdf_id": 4521,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380065,
//                 "date": "2024-08-19 ",
//                 "time": "18:32",
//                 "first_name": "Halyna",
//                 "last_name": "Poniatovska",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Investigator Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147533855,
//                 "pdf_id": 3970,
//                 "date": "2024-08-19",
//                 "time": "14:00",
//                 "first_name": "Aysegul ",
//                 "last_name": "Bilici Secmeler",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-326",
//                 "action": "IRT Not Completed Training",
//                 "heading": "IRT Not Completed Training"
//             },
//             {
//                 "user_id": 2147534558,
//                 "pdf_id": 3968,
//                 "date": "2024-08-19",
//                 "time": "14:00",
//                 "first_name": "Renata",
//                 "last_name": "Smajdova",
//                 "user_type": "Site User-Blinded",
//                 "site_number": "210-220",
//                 "action": "IRT Not Completed Training",
//                 "heading": "IRT Not Completed Training"
//             },
//             {
//                 "user_id": 2147533018,
//                 "pdf_id": 4521,
//                 "date": "2024-08-19",
//                 "time": "13:30",
//                 "first_name": "Maria Angelica",
//                 "last_name": "Rivera Núñez",
//                 "user_type": "Investigator-Blinded",
//                 "site_number": "210-202",
//                 "action": "IRT Not Completed Training",
//                 "heading": "IRT Not Completed Training"
//             },
//             {
//                 "user_id": 2147537024,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380025,
//                 "date": "2024-08-19 ",
//                 "time": "10:56",
//                 "first_name": "Stepan",
//                 "last_name": "Cherniaiev",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537024,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380021,
//                 "date": "2024-08-19 ",
//                 "time": "10:53",
//                 "first_name": "Stepan",
//                 "last_name": "Cherniaiev",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             },
//             {
//                 "user_id": 2147537024,
//                 "pdf_id": 3970,
//                 "action": "Article opened",
//                 "auto_mail": 0,
//                 "staticpdf_id": 380003,
//                 "date": "2024-08-19 ",
//                 "time": "05:17",
//                 "first_name": "Stepan",
//                 "last_name": "Cherniaiev",
//                 "user_type": "Site unblinded pharmacist",
//                 "site_number": "210-245",
//                 "file_type": "video",
//                 "pdfTitle": "IRT video training - Pharmacist Role",
//                 "subTitle": "MANDATORY Video for the indicated role to achieve certification",
//                 "allow_video": 0,
//                 "heading": "Content Opened"
//             }
//         ]
//     }



// ]